[aws]
symbol = "îŒ½  "
disabled = false

[character]
success_symbol = '[âœ](bold green)'
error_symbol = "[âœ](bold red) "

[cmd_duration]
min_time = 1_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
read_only = " ï ½"

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[elixir]
symbol = "î‰µ "
disabled = false

[git_branch]
symbol = "ï˜ "

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = true

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 50
style = "bold dimmed white"
disabled = false

[nix_shell]
symbol = "ï‹œ "
format = 'via [$symbol( \($name\))]($style) '
# format = 'via [â˜ƒï¸ $state( \($name\))](bold blue) 
disabled = false

[nodejs]
symbol = "î‰ "
disabled = true

[os]
format = "on $symbol "
style = "bold blue"
disabled = false

[os.symbols]
Arch = "ğŸ—ï¸ "
Debian = "ğŸŒ€ "
Manjaro = "ğŸ¥­ "
NixOS = "â„ï¸ "
Ubuntu = "ğŸ¯ "

[package]
symbol = "ï£– "
disabled = true

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[shell]
fish_indicator = "ïœ¹"
unknown_indicator = "mystery shell"
disabled = true

[username]
style_user = "bold dimmed blue"
show_always = true

